name: sync-notion-to-github

on:

  schedule:
    - cron: '0 0 * * *' # every day at 00:00 UTC

  workflow_dispatch:
  push:
    branches: [ "main" ]
    # paths:
    #   - 'posts/**'
    paths-ignore:
      - 'log/**'


jobs:
  sync:

    runs-on: ubuntu-latest
    env:
      Name: heziah

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        # path: "github"

    # - name: Checkout repository
    #   uses: actions/checkout@v3
    #   with:
    #     repository: 'YouXam/Notion-GitHub-Sync'
    #     path: "notion-sync"

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r notion/requirements.txt

    - name: Sync Notion to Github
      run:
        python ${{ github.workspace }}/notion/main.py ${{ github.workspace }}/posts/ ${{ secrets.NOTION_TOKEN }} $Name

    - name: Commit and push if changes
      run: |
        cd ${{ github.workspace }}
        git config --local user.email $Name"@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -F change.log
        git push